# in .cargo/config.toml
# 用于配置不同主机平台的构建命令,
# 每个平台的链接器不同, 导致编译器无法正确编译

[target.'cfg(target_os = "linux")']
rustflags = ["-C", "link-arg=-nostartfiles"]

[target.'cfg(target_os = "windows")']
rustflags = ["-C", "link-args=/ENTRY:_start /SUBSYSTEM:console"]

[target.'cfg(target_os = "none")']
runner = "bootimage runner"

[build]
# 告知编译器自动调用该配置
target = "x86_64.json"

# 且该配置项仅nightly版本支持这一特新
[unstable]
# 启用compiler_builtins中默认被禁用的特性
build-std-features = ["compiler-builtins-mem"]
# 该配置会告知cargo需要编译core和compiler_builtins
build-std = ["core", "compiler_builtins", "alloc"]
